### ISSUE TITLE
Add email verification

### ISSUE THREAD

**Issue by bluepichu** [bluepichu/a-la-mod#10]
Presumably, we don't want people spamming someone else's email.

**Comment by bluepichu** [comment]
It may also be good to allow the server to startup in some kind of development mode which would (among other things) prevent this from occurring to allow us to easily make user accounts.

**Comment by bluepichu** [comment]
Perhaps SendGrid would be useful here?

**Comment by zwade** [comment]
Did you ever get the account verified @bluepichu ?

**Comment by zwade** [comment]
we may want some more functionality for this, but for the time being, its done
