### ISSUE TITLE
Scroll to bottom after sending or receiving a message

### ISSUE THREAD

**Issue by bluepichu** [bluepichu/a-la-mod#58]
Currently, it remains in place, which causes new messages to come in unnoticed sometimes.

Also, you may only want to scroll to bottom if you're already at the bottom.

**Comment by zwade** [comment]
Also fix it so that when you scroll up too hard, it populates your history with a bunch of empty messages.

**Comment by zwade** [comment]
Also maybe just fix the wonky scrolling

**Comment by bluepichu** [comment]
Empty messages?  Where?

**Comment by bluepichu** [comment]
Rebundled with #66
